server:
  port: 8080
spring:
  activemq:
    broker-url: tcp://localhost:61616
  datasource:
    initialization-mode: never
    username: sa
    password:
    url: jdbc:h2:mem:orders
    platform: org.hibernate.dialect.H2Dialect
    driver-class-name: org.h2.Driver

  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    database: h2